// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2I8B_LKSduxwAJy3aDsl3eyk6b6R_I7o',
    appId: '1:420179820791:web:65da52df657626c45853f2',
    messagingSenderId: '420179820791',
    projectId: 'mood-tracker-ce619',
    authDomain: 'mood-tracker-ce619.firebaseapp.com',
    storageBucket: 'mood-tracker-ce619.firebasestorage.app',
    measurementId: 'G-GG0VPB3Q3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbQ3j9dXJZdcpjoNiIck168b3CAtjIucU',
    appId: '1:420179820791:android:19fdb641e7e3e14b5853f2',
    messagingSenderId: '420179820791',
    projectId: 'mood-tracker-ce619',
    storageBucket: 'mood-tracker-ce619.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsVVoKOUpEW1qQmNcH70qB-7MizatKklI',
    appId: '1:420179820791:ios:d97cb111804bd4175853f2',
    messagingSenderId: '420179820791',
    projectId: 'mood-tracker-ce619',
    storageBucket: 'mood-tracker-ce619.firebasestorage.app',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsVVoKOUpEW1qQmNcH70qB-7MizatKklI',
    appId: '1:420179820791:ios:d97cb111804bd4175853f2',
    messagingSenderId: '420179820791',
    projectId: 'mood-tracker-ce619',
    storageBucket: 'mood-tracker-ce619.firebasestorage.app',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2I8B_LKSduxwAJy3aDsl3eyk6b6R_I7o',
    appId: '1:420179820791:web:7a830e6ba77ce7805853f2',
    messagingSenderId: '420179820791',
    projectId: 'mood-tracker-ce619',
    authDomain: 'mood-tracker-ce619.firebaseapp.com',
    storageBucket: 'mood-tracker-ce619.firebasestorage.app',
    measurementId: 'G-4B2GK5D2QB',
  );
}
